version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: todo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sofofrootpassword
      MYSQL_DATABASE: sofof_todo_db
      MYSQL_USER: sofof_todo_user
      MYSQL_PASSWORD: sofof_todo_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: